import { PROD_GEOSERVER_URL } from '@/lib/constants'
import type { Legend, LegendRule, Symbolizer } from '@/lib/types/geoserver-types'

/**
 * Build a WMS GetLegendGraphic URL for a given layer
 * @param layer - Layer name (e.g., 'hazards:quaternaryfaults_test')
 * @param baseUrl - Base GeoServer URL (defaults to PROD_GEOSERVER_URL)
 * @param extraParams - Additional query params (e.g. BBOX/LEGEND_OPTIONS for content-dependent legends)
 * @returns Complete WMS GetLegendGraphic URL
 * @example
 * buildGetLegendGraphicUrl('hazards:quaternaryfaults_test')
 * // => 'https://geoserver.../wms?service=WMS&request=GetLegendGraphic&format=application/json&layer=hazards:quaternaryfaults_test'
 */
export function buildGetLegendGraphicUrl(
    layer: string,
    baseUrl: string = PROD_GEOSERVER_URL,
    extraParams?: Record<string, string>
): string {
    const params = new URLSearchParams({
        service: 'WMS',
        request: 'GetLegendGraphic',
        format: 'application/json',
        layer,
        version: '1.3.0',
        ...extraParams,
    })
    return `${baseUrl}/wms?${params.toString()}`
}

/** Split a (possibly comma-separated) WMS layer name into individual GeoServer sublayer names. */
export function splitSublayerNames(layerName: string): string[] {
    return String(layerName).split(',').map(n => n.trim()).filter(Boolean)
}

/** GetLegendGraphic rules for one GeoServer sublayer. */
export interface SublayerLegendRules {
    layerName: string
    rules: LegendRule[]
}

/**
 * Fetch GetLegendGraphic rules for each sublayer of a (possibly comma-separated) WMS layer name.
 * GetLegendGraphic only accepts one layer per request, so this splits the name, fetches each, and
 * returns the rules grouped by sublayer. Non-OK / non-JSON / empty responses are skipped so one bad
 * sublayer never drops the rest. Callers map the rules into their own preview/swatch shapes.
 * @param wmsUrl - Full WMS endpoint (e.g. `${PROD_GEOSERVER_URL}/wms`)
 * @param extraParams - Extra GetLegendGraphic params (BBOX/LEGEND_OPTIONS, …)
 */
export async function fetchLegendRulesBySublayer(
    wmsUrl: string,
    layerName: string,
    extraParams?: Record<string, string>
): Promise<SublayerLegendRules[]> {
    const groups: SublayerLegendRules[] = []
    for (const ln of splitSublayerNames(layerName)) {
        const params = new URLSearchParams({
            service: 'WMS',
            request: 'GetLegendGraphic',
            format: 'application/json',
            layer: ln,
            version: '1.3.0',
            ...extraParams,
        })
        try {
            const response = await fetch(`${wmsUrl}?${params.toString()}`, {
                method: 'GET',
                headers: { Accept: 'application/json' },
            })
            if (!response.ok) continue
            if (!response.headers.get('content-type')?.includes('application/json')) continue
            const legendData: Legend = await response.json()
            const rules = legendData?.Legend?.[0]?.rules || []
            if (rules.length > 0) groups.push({ layerName: ln, rules })
        } catch {
            continue
        }
    }
    return groups
}

/**
 * Extract the literal value from a WMS rule filter string
 * Filters are in the format: "[fieldname = 'value']"
 * @param filter - WMS rule filter string
 * @returns Extracted value or undefined
 * @example
 * extractWMSLiteralValue("[qffhazardunit = 'U15KWCqff']")
 * // => "U15KWCqff"
 *
 * extractWMSLiteralValue("[lssunit = 'H']")
 * // => "H"
 */
export function extractWMSLiteralValue(filter: string): string | undefined {
    try {
        const match = filter.match(/=\s*'([^']+)'/)
        return match?.[1]
    } catch (error) {
        console.warn('Error extracting literal value from WMS rule filter:', error)
        return undefined
    }
}

/**
 * Check if a WMS legend rule is an auto-generated default symbolizer
 * Auto-generated defaults typically have:
 * - Single Point symbolizer
 * - A mark element
 * - No fill or stroke styling
 * These are placeholder rules that should be filtered out
 * @param symbolizers - Array of symbolizers from WMS rule
 * @returns True if this is an auto-generated default
 * @example
 * const rule = {
 *     symbolizers: [{
 *         Point: {
 *             graphics: [{
 *                 mark: 'circle'
 *             }]
 *         }
 *     }]
 * }
 * isAutoGeneratedDefaultSymbolizer(rule.symbolizers) // => true (no fill/stroke)
 */
export function isAutoGeneratedDefaultSymbolizer(symbolizers: Symbolizer[] | undefined): boolean {
    if (!symbolizers || symbolizers.length !== 1) {
        return false
    }

    const symbolizer = symbolizers[0]
    const pointSymbolizer = symbolizer?.Point

    // Check for Point symbolizer with mark but no fill/stroke
    if (pointSymbolizer && pointSymbolizer.graphics?.length === 1) {
        const graphic = pointSymbolizer.graphics[0]
        return Boolean(
            graphic?.mark &&
            !graphic.fill &&
            !graphic.stroke
        )
    }

    return false
}

/**
 * Fetch WMS legend data from GeoServer
 * @param layer - Layer name (e.g., 'hazards:quaternaryfaults_test')
 * @param baseUrl - Base GeoServer URL (defaults to PROD_GEOSERVER_URL)
 * @returns Parsed legend data or null if fetch fails
 */
export async function fetchWMSLegendData(
    layer: string,
    baseUrl: string = PROD_GEOSERVER_URL
): Promise<any | null> {
    try {
        const url = buildGetLegendGraphicUrl(layer, baseUrl)
        const response = await fetch(url)

        if (!response.ok) {
            console.warn(`WMS legend fetch failed for ${layer}: HTTP ${response.status}`)
            return null
        }

        return await response.json()
    } catch (error) {
        console.warn(`Error fetching WMS legend for ${layer}:`, error)
        return null
    }
}
