import { PROD_GEOSERVER_URL } from '@/lib/constants'

/**
 * Build a WMS GetLegendGraphic URL for a given layer
 * @param layer - Layer name (e.g., 'hazards:quaternaryfaults_test')
 * @param baseUrl - Base GeoServer URL (defaults to PROD_GEOSERVER_URL)
 * @returns Complete WMS GetLegendGraphic URL
 * @example
 * buildGetLegendGraphicUrl('hazards:quaternaryfaults_test')
 * // => 'https://geoserver.../wms?service=WMS&request=GetLegendGraphic&format=application/json&layer=hazards:quaternaryfaults_test'
 */
export function buildGetLegendGraphicUrl(
    layer: string,
    baseUrl: string = PROD_GEOSERVER_URL
): string {
    const params = new URLSearchParams({
        service: 'WMS',
        request: 'GetLegendGraphic',
        format: 'application/json',
        layer
    })
    return `${baseUrl}wms?${params.toString()}`
}

/**
 * Extract the literal value from a WMS rule filter string
 * Filters are in the format: "[fieldname = 'value']"
 * @param filter - WMS rule filter string
 * @returns Extracted value or undefined
 * @example
 * extractWMSLiteralValue("[qffhazardunit = 'U15KWCqff']")
 * // => "U15KWCqff"
 *
 * extractWMSLiteralValue("[lssunit = 'H']")
 * // => "H"
 */
export function extractWMSLiteralValue(filter: string): string | undefined {
    try {
        const match = filter.match(/=\s*'([^']+)'/)
        return match?.[1]
    } catch (error) {
        console.warn('Error extracting literal value from WMS rule filter:', error)
        return undefined
    }
}

/**
 * Check if a WMS legend rule is an auto-generated default symbolizer
 * Auto-generated defaults typically have:
 * - Single Point symbolizer
 * - A mark element
 * - No fill or stroke styling
 * These are placeholder rules that should be filtered out
 * @param symbolizers - Array of symbolizers from WMS rule
 * @returns True if this is an auto-generated default
 * @example
 * const rule = {
 *     symbolizers: [{
 *         Point: {
 *             graphics: [{
 *                 mark: 'circle'
 *             }]
 *         }
 *     }]
 * }
 * isAutoGeneratedDefaultSymbolizer(rule.symbolizers) // => true (no fill/stroke)
 */
export function isAutoGeneratedDefaultSymbolizer(symbolizers: any[]): boolean {
    if (!symbolizers || symbolizers.length !== 1) {
        return false
    }

    const symbolizer = symbolizers[0]
    const pointSymbolizer = symbolizer?.Point

    // Check for Point symbolizer with mark but no fill/stroke
    if (pointSymbolizer && pointSymbolizer.graphics?.length === 1) {
        const graphic = pointSymbolizer.graphics[0]
        return Boolean(
            graphic?.mark &&
            !graphic.fill &&
            !graphic.stroke
        )
    }

    return false
}

/**
 * Fetch WMS legend data from GeoServer
 * @param layer - Layer name (e.g., 'hazards:quaternaryfaults_test')
 * @param baseUrl - Base GeoServer URL (defaults to PROD_GEOSERVER_URL)
 * @returns Parsed legend data or null if fetch fails
 */
export async function fetchWMSLegendData(
    layer: string,
    baseUrl: string = PROD_GEOSERVER_URL
): Promise<any | null> {
    try {
        const url = buildGetLegendGraphicUrl(layer, baseUrl)
        const response = await fetch(url)

        if (!response.ok) {
            console.warn(`WMS legend fetch failed for ${layer}: HTTP ${response.status}`)
            return null
        }

        return await response.json()
    } catch (error) {
        console.warn(`Error fetching WMS legend for ${layer}:`, error)
        return null
    }
}
