export const HAZARDS_REPORT_CONTENT = {
    coverPageIntro: `This report contains geologic hazard information and data from the Utah Geological Survey (UGS) and other sources for the area of interest shown on the map below. The data can be used to identify mapped geologic hazards in an area, understand what the hazards are, and conduct site-specific investigations. This report is not a substitute for site-specific geologic hazards and geotechnical engineering investigations by a qualified, Utah-licensed consultant. These investigations provide valuable information on a site's geologic conditions that may affect or be affected by development. They also proved the type and susceptibility of geologic hazards at a site, both during construction and over the life of the development. See your local city or county building department for details on geologic hazard and engineering investigation requirements and UGS Circular 128 (<a href="https://doi.org/10.34191/C-128" target="_blank" rel="noopener noreferrer">https://doi.org/10.34191/C-128</a>) for guidelines for investigating geologic hazards and preparing engineering geology reports.<br><br>Since 1850, at least 6172 deaths and an undetermined financial cost have been attributed to geologic hazards in Utah. Damages resulting from many geologic hazards are often not covered by property or other insurance. In almost all cases, it is more cost effective to investigate and characterize potential hazards and implement appropriate mitigation, rather than rely on additional maintenance over the life of a project and/or incur costly construction change orders and other financial costs.`,
    disclaimer: `<strong>Disclaimer:</strong> The Utah Department of Natural Resources, Utah Geological Survey, makes no warranty, expressed or implied, regarding the suitability of this product for a particular use, and does not guarantee accuracy or completeness of the data. The Utah Department of Natural Resources, Utah Geological Survey, shall not be liable under any circumstances for any direct, indirect, special, incidental, or consequential damages with respect to claims by users of this product. The Utah Geological Survey does not endorse any products or manufacturers. Reference to any specific commercial product, process, service, or company by trade name, trademark, or otherwise, is for informational purposes only and does not constitute endorsement or recommendation by the Utah Geological Survey.`,
    summary: {
        intro: `Geologic hazards affect Utah, negatively impacting life safety, health, property, and the state's economy. These hazards are geologic conditions that present a risk to life or of substantial loss or damage of real property, and are generally within five categories: landslide, earthquake (including seismic ground shaking and liquefaction), flooding, problem soil and rock, and volcanic hazards. Although many geologic hazards are not life threatening, they are often costly when not recognized and properly accommodated and mitigated in project planning and design, and may result in additional, significant construction and/or future maintenance costs and injury or death.<br><br>However, we can live and deal with geologic hazards by understanding what they are, where they exist, how large or difficult they are, and how to effectively mitigate them. Detailed geologic hazard mapping is available for limited areas and for specific hazards in Utah, and additional mapping is ongoing. This report represents geologic hazard data extracted from the Utah Geologic Hazards Database of current geologic hazard mapping by the UGS for part of Utah and from other sources at the date and time indicated on the cover page. For each of the major geologic hazard categories (earthquake, landslide, flooding, and problem soil and rock) mapped in Utah, a summary page is available that describes the hazard category and the individual types of hazards within that category. The detailed pages following the summary are for each mapped hazard type and contain a brief description of that hazard type, a map of your area of interest and the mapped hazard susceptibility, a brief discussion on the susceptibility rankings and their meaning, and a list of references and other information for that hazard type. <strong>The absence of data does not imply that no geologic hazard or hazards exist.</strong> Additional geologic hazard mapping is on-going and will be added to the database as it is finalized.`,
        closing: `The database is updated when new geologic hazard mapping is published by the UGS, usually in urban areas using 7.5-minute map quadrangles as comprehensive geologic hazard map sets. If mapping is not available for your area of interest at the time this report was created, check the UGS website for updates or contact us at (801) 537-3300 or <a href="https://geology.utah.gov/about-us/ask-a-geologist" target="_blank" rel="noopener noreferrer">https://geology.utah.gov/about-us/ask-a-geologist</a>.`
    },

    otherResources: `
        <div class="space-y-4">
            <div>
                <h3 class="text-xl font-semibold">Utah Geological Survey</h3>
                <p>For information on geologic hazards, contact the UGS online at <a href="https://geology.utah.gov/about-us/ask-a-geologist/" target="_blank" rel="noopener noreferrer">https://geology.utah.gov/about-us/ask-a-geologist/</a> or by telephone at (801) 537-3300 and for southern Utah at (435) 865-9036.</p>
                <p><em>The Guidelines for Investigating Geologic Hazards and Preparing Engineering-Geology Reports with a Suggested Approach to Geologic-Hazard Ordinances in Utah</em> (UGS Circular 128, <a href="https://doi.org/10.34191/C-128" target="_blank" rel="noopener noreferrer">https://doi.org/10.34191/C-128</a>) provides geologic and geotechnical consultants, local government officials, and land owners with comprehensive information on how to conduct appropriate and effective investigations of various geologic hazards before building and infrastructure design and construction. These guidelines were developed to reduce the life safety risk and overall cost of geologic hazards to Utahns and have been adopted by numerous cities and counties in Utah. The UGS strongly recommends that all development incorporates these guidelines in their planning, design, and construction.</p>
                <p>The UGS GeoData Archive (<a href="https://geodata.geology.utah.gov" target="_blank" rel="noopener noreferrer">https://geodata.geology.utah.gov</a>) contains scanned documents related to Utah geology, consultant geologic and geotechnical reports, photographs, and other digital materials from our files and those gathered from other agencies or organizations. Most of the items in the archive have not been formally published and are not available elsewhere.</p>
                <p>The UGS Utah Aerial Imagery Collection (<a href="https://imagery.geology.utah.gov" target="_blank" rel="noopener noreferrer">https://imagery.geology.utah.gov</a>) contains aerial photography (air photos) across Utah taken from 1935 to 2024, about half of the collection dates to before 1960.</p>
                <p>The Utah Geologic Map Portal (<a href="https://geomap.geology.utah.gov" target="_blank" rel="noopener noreferrer">https://geomap.geology.utah.gov</a>) contains geologic maps that show the mapped geologic units across the state.</p>
            </div>
            <div>
                <p>Building Codes (the IBC and IRC with amendments are adopted statewide by Utah law),</p>
                <ul class="list-disc list-inside">
                    <li>State of Utah Adopted Building Codes in Law: <a href="https://le.utah.gov/xcode/Title15A/15A.html" target="_blank" rel="noopener noreferrer">https://le.utah.gov/xcode/Title15A/15A.html</a>.</li>
                    <li>International Building Code (2024, International Code Council): <a href="https://codes.iccsafe.org/content/IBC2024V2.0" target="_blank" rel="noopener noreferrer">https://codes.iccsafe.org/content/IBC2024V2.0</a>.</li>
                    <li>International Residential Code (2024, International Code Council): <a href="https://codes.iccsafe.org/content/IRC2024V2.0" target="_blank" rel="noopener noreferrer">https://codes.iccsafe.org/content/IRC2024V2.0</a>.</li>
                </ul>
            </div>
            <div>
                <h3 class="text-xl font-semibold">Professional Licensing</h3>
                <p>When selecting a geologist or engineer consultant and a construction contractor, make sure they are licensed to practice in Utah using the Utah Division of Occupational & Professional Licensing website at <a href="https://secure.utah.gov/llv/search/index.html" target="_blank" rel="noopener noreferrer">https://secure.utah.gov/llv/search/index.html</a>. For more information, see <a href="https://dopl.utah.gov/" target="_blank" rel="noopener noreferrer">https://dopl.utah.gov/</a>.</p>
            </div>
        </div>
    `,
};