import { useQuery } from '@tanstack/react-query'
import { createSVGSymbol } from '@/lib/legend/symbol-generator'
import { Legend } from '@/lib/types/geoserver-types'
import { CompositeSymbolResult } from '@/lib/legend/symbolizers/line'
import { extractWMSLiteralValue, isAutoGeneratedDefaultSymbolizer } from '@/lib/legend/wms-legend-service'

interface WMSLegendPreview {
    label: string
    literalValue?: string
    html?: SVGSVGElement | CompositeSymbolResult
}

/**
 * Hook to fetch WMS legend data directly from GeoServer
 * @param layerName - The name of the WMS layer the format is typically "workspace:layername" or just "layername"
 * @param wmsUrl - The base URL of the WMS service
 * @returns An object containing the legend preview data, loading state, and any error encountered
 */
export const useWMSLegend = (layerName: string, wmsUrl: string) => {
    const fetchLegendData = async (): Promise<WMSLegendPreview[]> => {
        if (!layerName || !wmsUrl) {
            return []
        }
        // Construct the WMS GetLegendGraphic URL
        const legendUrl = `${wmsUrl}?service=WMS&request=GetLegendGraphic&format=application/json&layer=${layerName}`

        try {
            const response = await fetch(legendUrl, {
                method: 'GET',
                headers: { Accept: 'application/json' },
            })

            if (!response.ok) {
                throw new Error(`HTTP error! Status: ${response.status} for layer ${layerName}`)
            }

            const legendData: Legend = await response.json()
            const rules = legendData?.Legend?.[0]?.rules || []

            if (rules.length === 0) {
                console.warn('No rules found in legend data for layer:', layerName)
                return []
            }

            // Map through all rules and generate preview objects
            const previews: WMSLegendPreview[] = rules.map((rule) => {
                const isAutoGeneratedDefault = isAutoGeneratedDefaultSymbolizer(rule.symbolizers)
                const label = rule.title || rule.name
                const literalValue = extractWMSLiteralValue(rule.filter)

                if (isAutoGeneratedDefault) {
                    return {
                        label: label,
                        literalValue: literalValue,
                    }
                }

                const svg = createSVGSymbol(rule.symbolizers)

                return {
                    label: label,
                    literalValue: literalValue,
                    html: svg,
                }
            })

            return previews
        } catch (error) {
            console.error('Error fetching WMS legend data:', error)
            throw error
        }
    }

    const { data: preview = [], isLoading, error } = useQuery({
        queryKey: ['wmsLegend', layerName, wmsUrl],
        queryFn: fetchLegendData,
        enabled: !!layerName && !!wmsUrl,
        staleTime: 1000 * 60 * 60, // Cache for 1 hour
    })

    return { preview, isLoading, error }
}