import { useQuery } from '@tanstack/react-query';
import { RendererFactory } from '@/lib/legend/renderer-factory';
import { createSVGSymbol } from '@/lib/legend/symbol-generator';
import { createRasterSymbol } from '@/lib/legend/symbolizers/raster';
import { Legend, LegendRule } from '@/lib/types/geoserver-types';
import { RegularLayerRenderer } from '@/lib/types/mapping-types';
import { queryKeys } from '@/lib/query-keys';

function findRasterRule(rules: LegendRule[]): LegendRule | undefined {
    return rules.find(rule =>
        rule.symbolizers?.some(s => s.Raster?.colormap?.entries?.length)
    );
}

/**
 * Check if a WMS legend rule is an auto-generated default symbolizer
 */
function isAutoGeneratedDefaultSymbolizer(rule: LegendRule): boolean {
    const symbolizer = rule.symbolizers?.[0]?.Point;
    const graphic = symbolizer?.graphics?.[0];
    return Boolean(
        rule.symbolizers?.length === 1 &&
        symbolizer &&
        symbolizer.graphics?.length === 1 &&
        graphic?.mark && !graphic.fill && !graphic.stroke
    );
}

export type PreviewItem = {
    html?: HTMLElement | SVGSVGElement | null;
    label?: string;
    title?: string;
    isComposite?: boolean;
    /** Group heading row (no swatch). Used to delineate sublayers in a merged multi-sublayer legend. */
    sectionTitle?: string;
};

/** Fetches GeoServer GetLegendGraphic JSON and converts each rule into a preview item.
 * `layerLabels` maps a GeoServer sublayer name to a friendly heading (e.g. 'Wells'); when the layer
 * has more than one sublayer, each group's swatches are preceded by a sectionTitle row. */
const useLegendPreview = (url: string, layerName?: string, skip?: boolean, legendUnit?: string, layerLabels?: Record<string, string>) => {
    const fetchLegendData = async (): Promise<PreviewItem[]> => {
        if (!url || !layerName) {
            return [];
        }

        // A layer can bundle multiple GeoServer sublayers (comma-separated). GetLegendGraphic takes
        // one layer per request, so fetch each name and merge the rules into one preview list.
        const layerNames = String(layerName).split(',').map(n => n.trim()).filter(Boolean);
        const showSectionHeaders = layerNames.length > 1;
        const allPreviews: PreviewItem[] = [];

        for (const ln of layerNames) {
            const legendUrl = `${url}?service=WMS&request=GetLegendGraphic&format=application/json&layer=${ln}&version=1.3.0`;

            try {
                const response = await fetch(legendUrl, {
                    method: 'GET',
                    headers: { Accept: 'application/json' },
                });

                if (!response.ok) {
                    continue;
                }

                const contentType = response.headers.get('content-type');
                if (!contentType?.includes('application/json')) {
                    continue;
                }

                const legendData: Legend = await response.json();
                const rules = legendData?.Legend?.[0]?.rules || [];

                if (rules.length === 0) {
                    continue;
                }

                // Delineate each sublayer's swatches in a merged legend with a heading row.
                const sectionTitle = layerLabels?.[ln];
                if (showSectionHeaders && sectionTitle) {
                    allPreviews.push({ sectionTitle });
                }

                // Raster: bypass RendererFactory (would crush the bar to a 32×22 swatch).
                const rasterRule = findRasterRule(rules);
                if (rasterRule) {
                    const html = createRasterSymbol(rasterRule.symbolizers, { unit: legendUnit });
                    allPreviews.push({ html });
                    continue;
                }

                // Convert rules to preview format
                const previews: RegularLayerRenderer[] = rules.map((rule) => {
                    const isAutoGenerated = isAutoGeneratedDefaultSymbolizer(rule);
                    const label = rule.title || rule.name;

                    if (isAutoGenerated) {
                        // Empty SVG for auto-generated defaults
                        const emptySvg = document.createElementNS("http://www.w3.org/2000/svg", "svg");
                        emptySvg.setAttribute("width", "32");
                        emptySvg.setAttribute("height", "20");
                        emptySvg.style.visibility = "hidden";
                        return {
                            type: 'regular-layer-renderer' as const,
                            label,
                            renderer: emptySvg,
                            id: ln,
                            url,
                        };
                    }

                    return {
                        type: 'regular-layer-renderer' as const,
                        label,
                        renderer: createSVGSymbol(rule.symbolizers),
                        id: ln,
                        url,
                    };
                });

                // Generate preview HTML for each renderer
                const finalPreviews = await Promise.all(
                    previews.map(async (item) => {
                        try {
                            return await RendererFactory.createPreview(item);
                        } catch {
                            return null;
                        }
                    })
                );

                allPreviews.push(...finalPreviews.flatMap((p): PreviewItem[] => p ? [p] : []));
            } catch {
                continue;
            }
        }

        return allPreviews;
    };

    const { data: preview = [], isLoading, error } = useQuery({
        queryKey: queryKeys.layers.legend(layerName || '', url),
        queryFn: fetchLegendData,
        enabled: !!url && !!layerName && !skip,
        staleTime: 1000 * 60 * 60, // Cache for 1 hour
    });

    return { preview, isLoading, error };
};

export default useLegendPreview;